
version: '3'
services:
  database:
    image: postgres:14-alpine
    env_file:
      - .env
    container_name: kupipodariday
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - '5432:5432'
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    env_file:
      - .env
    depends_on:
      - database
    container_name: kupipodariday-backend
    networks:
      - backend-network
    ports:
      - '4001:4000'
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    depends_on:
      - backend
    container_name: kupipodariday-frontend
    ports:
      - '3001:3000'
    restart: always

networks:
  backend-network:
  
volumes:
  database: