
version: "3"

services:

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    env_file: .env
    ports:
      - '4000:3000'
    restart: always
    
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3001:3000"
    restart: always
   
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart:  always
    env_file: .env
